### ISSUE TITLE
Option to choose "Sprite"

### ISSUE THREAD

**Issue by muldjord** [Deckromancy/AnimatedEncoder#1]
UPDATE! I am unsure if you are even the developer of said website. I thought I saw your name on both but apparently I didn't. So just disregard this issue. Perhaps just delete it. Thank you.

----------

I started using the online apng converter at http://animatedpngs.com/ just the other day. I use it to assemble animated pngs for my Pebble smartwatch. I discovered that my apngs got garbled on the watch if I didn't choose the "sprite" option on the website. But now that option seems to have gone away and my pngs come out garbled again, therefore I can no longer use it with my Pebble pngs.

The pngs work just fine in Firefox, but not on the Pebble. Can you be convinced to add that "sprite" option back?

**Comment by Deckromancy** [comment]
Yes, AnimatedPNGs.com is mine as well. The new version auto detects when frame clears are needed if it can't recycle pixels with Over blending, but it does recycle when possible to be more efficient and cut sizes. It picks the most efficient mode for each frame automatically. Looking at the Pebble page it looks like someone has pointed out that pebble doesn't support the Dispose-to-Previous feature of Animated PNG, which would explain why it plays fine in Firefox, but not Pebble. Perhaps some advanced options to disable that disposal mode could solve the issue. I'll look into that as a fix, as I know allot of people might use it to build things for Pebble. I would prefer not to revert to the old way of requiring people to choose movie or sprite, but I might make an alternate page with the old version if it can't be sorted out.

**Comment by muldjord** [comment]
Thank you for your answer. In the meantime I managed to patch apngasm to not use the "dispose-to-previous" so I can now use a cli tool instead, which in the end is more convenient for me.

But for others, maybe less tech minded (and terminal approving) than me, I think it would be appreciated to have a version of animatedpngs.com that would allow it to bypass the "dispose-to-previous".

Also, thank you for making the website available. It's very useful!

**Comment by Deckromancy** [comment]
You're welcome, and thank you for reporting the issue. It should save confusion and headaches for others. I have added an option under "Advanced" if you scroll down and select "Compatibility for pebble smartwatch." This will set a parameter to disable the dispose-to-previous feature. My guess is that they disabled this feature due to limited resources on the watch and saving memory by not retaining the previous frame data.
If you don't mind testing it and confirming that the result displays properly on pebble, it would be greatly appreciated.

**Comment by muldjord** [comment]
Tested it and it works brilliantly now when showing them on the Pebble. Thank you! :)

**Comment by Deckromancy** [comment]
Great, thank you for testing. I'll now mark this as resolved.
