### ISSUE TITLE
Setting loop count in website

### ISSUE THREAD

**Issue by midzer** [Deckromancy/AnimatedEncoder#3]
Hi,
an advanced option on the website to set the amount of loops for an APNG would be great. 0 could act as default for infinite looping.

Greets,
midzer

**Comment by Deckromancy** [comment]
Hello,
Thanks for the input. I went ahead and built in loop control and you can use it on the website now under advanced. 0 or leaving it blank will be infinite. It always defaulted to infinite looping before because that was by far the most common.

**Comment by midzer** [comment]
Just checked it out and it works fine for me. Awesome!
