### ISSUE TITLE
Unexpected result for input data

### ISSUE THREAD

**Issue by midzer** [Deckromancy/AnimatedEncoder#4]
Hi again,
library working fine. Miserably with some .png animated result is just a transparent single picture with only ~3kb. 

Used following non-default settings:
Brute-Force: true
Quality: 100%
Dithering: None
Loops: 1

You can find the pack at https://filebin.net/7zqktln5jktvihmo/grape.zip

Thanks for your time and greets from Munich,
midzer

**Comment by Deckromancy** [comment]
Thank you for reporting the issue. I was able to reproduce the issue with your image frames/settings. This should be fixed now and you can build your Animated PNG with those settings.

**Comment by midzer** [comment]
Working smoothly now. Merci for your effort
